name: $(image)-$(Date:yyyyMMdd)-$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - release
    - master
  tags:
    exclude:
    - '*'
  paths:
    include:
    - library/tengine/*

pr:
  branches:
    include:
    - release
    - master
  paths:
    include:
    - library/tengine/*

variables:
  - group: build
  - name: image
    value: tengine

pool:
  name: Default

resources:
- repo: self

stages:
- template: ../../.azuredevops/template/docker-build-pipelines.yml
  parameters:
    BashfilePath: "library/$(image)/build.sh"

