name: $(image)-$(Date:yyyyMMdd)-$(Rev:r)

trigger: 
  batch: true
  branches:
    include:
    - release
    - master
  tags:
    exclude:
    - '*'
  paths:
    include:
    - nginx/*

pr:
  branches:
    include:
    - release
    - master
  paths:
    include:
    - nginx/*

variables:
  - group: build
  - name: image
    value: nginx

pool:
  name: Default

resources:
- repo: self

stages:
- template: template/docker-build-pipelines.yml
