name: $(image)-$(Date:yyyyMMdd)-$(Rev:r)

trigger: 
  batch: true
  branches:
    include:
    - release
    - master
  tags:
    exclude:
    - '*'
  paths:
    include:
    - library/nginx/*

pr:
  branches:
    include:
    - release
    - master
  paths:
    include:
    - library/nginx/*

variables:
  - group: build
  - name: image
    value: nginx

pool:
  name: Default

resources:
- repo: self

stages:
- template: .azuredevops/template/docker-build-pipelines.yml@self
  parameters:
    BashfilePath: "library/$(image)/build.sh"
 
