stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    workspace:
      clean: all
    steps:
      - checkout: self
        clean: true
        fetchTags: true
      - task: Docker@2
        displayName: DockerLogin
        inputs:
          containerRegistry: docker.io
          command: login
          addPipelineData: false
          addBaseImageData: false
      - task: Bash@3
        displayName: 'DockerBuild'
        inputs:
          targetType: filePath
          filePath: ${{ parameters.BashfilePath }}
          arguments: 'build'
      - task: Bash@3
        displayName: 'DockerTest'
        inputs:
          targetType: filePath
          filePath: ${{ parameters.BashfilePath }}
          arguments: 'test'
      - task: Bash@3
        displayName: 'DockerPush'
        inputs:
          targetType: filePath
          filePath: ${{ parameters.BashfilePath }}
          arguments: 'push'
        condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/release'))

